import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,locale:'nb-NO'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route(/\/rest\/v1\//,r=>r.fulfill({status:200,contentType:'application/json',body:'[]'}));
await page.goto('http://127.0.0.1:4173/index.html',{waitUntil:'domcontentloaded'});
await page.locator('[data-poster-menu]').click();
await page.locator('[data-menu-profile]').click();
assert.equal(await page.locator('[data-profile-start]').isDisabled(),true);
await page.locator('[data-profile-group="service"] [data-value="sofa"]').click();
await page.locator('[data-profile-group="issues"] [data-value="stains"]').click();
await page.locator('[data-profile-group="issues"] [data-value="odor"]').click();
assert.equal(await page.locator('[data-profile-score]').textContent(),'2/2');
assert.equal(await page.locator('[data-profile-start]').isEnabled(),true);
await page.locator('[data-profile-start]').click();
assert.equal(await page.locator('.service-card.open').getAttribute('data-service'),'sofa');
await page.locator('[data-drawer-close]').click();
await page.locator('[data-poster-lang="ru"]').click();
await page.waitForTimeout(100);
await page.locator('[data-poster-menu]').click();
await page.waitForFunction(()=>document.querySelector('.sir-poster-drawer')?.classList.contains('open'));
await page.waitForTimeout(300);
await page.locator('[data-menu-profile]').click();
assert.equal((await page.locator('#sir-profile-title').textContent())?.trim(),'Создайте профиль чистоты');
assert.deepEqual(errors,[]);
await browser.close();
console.log('SIGNATURE PROFILE PASS');
