(() => {
const C=window.SIR_CONFIG; let sb=null,preview=false,currentRole='PREVIEW';
const login=document.getElementById('login'),app=document.getElementById('app'),main=document.getElementById('main');
const connected=!!(C.supabaseUrl&&C.supabasePublishableKey);
if(connected){sb=window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey);document.getElementById('setupNotice').classList.add('hidden');}

document.getElementById('previewBtn').addEventListener('click',()=>{preview=true;enter('PREVIEW');});
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!sb){alert('Сначала нужно подключить правильный проект Supabase SIR.');return;}const email=document.getElementById('email').value,password=document.getElementById('password').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){alert(error.message);return;}const {data:profile}=await sb.from('profiles').select('role,display_name').eq('id',data.user.id).single();currentRole=(profile?.role||'worker').toUpperCase();enter(currentRole);});
document.getElementById('logout').addEventListener('click',async()=>{if(sb&&!preview)await sb.auth.signOut();location.reload();});
document.getElementById('nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;document.querySelectorAll('#nav [data-view]').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.view);});
async function enter(role){login.classList.add('hidden');app.classList.remove('hidden');document.getElementById('roleBadge').textContent=role;render('dashboard');}
const money=n=>new Intl.NumberFormat('nb-NO').format(n||0)+' NOK';
const statusLabel={new:'Новый',under_review:'На рассмотрении',offer_sent:'Предложение отправлено',awaiting_confirmation:'Ждёт подтверждения',confirmed:'Подтверждён',scheduled:'Запланирован',in_progress:'В работе',completed:'Выполнен',cancelled_customer:'Отменён клиентом',cancelled_sir:'Отменён SIR',no_show:'Неявка'};
async function getOrders(){if(preview||!sb)return [];const {data,error}=await sb.from('orders').select('*').order('created_at',{ascending:false}).limit(100);if(error){console.error(error);return [];}return data||[];}
async function render(view){main.innerHTML='<div class="empty">Загрузка…</div>';if(view==='dashboard')return dashboard();if(view==='orders')return orders();if(view==='calendar')return calendar();if(view==='customers')return customers();if(view==='guide')return guide();if(view==='finance')return finance();if(view==='team')return team();if(view==='audit')return audit();if(view==='settings')return settings();}
async function dashboard(){const o=await getOrders(),today=new Date().toISOString().slice(0,10);const count=s=>o.filter(x=>x.status===s).length;const revenue=o.filter(x=>x.status==='completed'&&String(x.completed_at||'').startsWith(today)).reduce((a,x)=>a+(+x.final_price||0),0);main.innerHTML=`<div class="section-title"><div><h1>Главная</h1><p>Сегодняшняя работа и риски</p></div></div>${preview?'<div class="notice">Предпросмотр: реальная база заказов пока не подключена. Никакие клиентские данные в браузере не сохраняются.</div>':''}<div class="grid"><div class="card metric"><span>Новые</span><strong>${count('new')}</strong></div><div class="card metric"><span>Ждут подтверждения</span><strong>${count('awaiting_confirmation')}</strong></div><div class="card metric"><span>В работе</span><strong>${count('in_progress')}</strong></div><div class="card metric"><span>Выручка сегодня</span><strong>${money(revenue)}</strong></div></div><div class="panel"><div class="panel-head"><span>Требуют внимания</span><span class="mini">HIGH RISK / STOP всегда наверху</span></div>${o.length?orderTable(o.slice(0,8)):'<div class="empty">После подключения Supabase здесь появятся реальные заказы.</div>'}</div>`;}
function orderTable(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Заказ</th><th>Клиент</th><th>Услуга</th><th>Статус</th><th>Цена</th><th>Риск</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.order_no||'—')}</b></td><td>${esc(x.customer_name||'—')}<div class="mini">${esc(x.phone||'')}</div></td><td>${esc(x.service_type||x.service||'—')}</td><td>${statusLabel[x.status]||esc(x.status||'—')}</td><td>${x.final_price?money(x.final_price):x.preliminary_price?money(x.preliminary_price):'—'}</td><td><span class="risk ${(x.risk_level||'low').replace('_',' ')}">${esc((x.risk_level||'LOW').toUpperCase())}</span></td></tr>`).join('')}</tbody></table></div>`;}
async function orders(){const o=await getOrders();main.innerHTML=`<div class="section-title"><div><h1>Заказы</h1><p>Полный цикл: заявка → предложение → подтверждение → работа</p></div><div class="toolbar"><button class="btn">+ Ручной заказ</button></div></div>${o.length?`<div class="panel">${orderTable(o)}</div>`:'<div class="card empty">Реальные заказы появятся после подключения базы SIR. Старый localStorage здесь намеренно не используется.</div>'}`;}
async function calendar(){const o=await getOrders();const now=new Date(),y=now.getFullYear(),m=now.getMonth();const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();const by={};o.forEach(x=>{const d=(x.scheduled_start||'').slice(0,10);if(d)(by[d]??=[]).push(x);});const names=['ВС','ПН','ВТ','СР','ЧТ','ПТ','СБ'];let cells='';for(let d=1;d<=days;d++){const dt=new Date(y,m,d),key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;cells+=`<div class="day"><b>${d} ${names[dt.getDay()]}</b>${(by[key]||[]).map(x=>`<div class="slot">${String(x.scheduled_start).slice(11,16)} · ${esc(x.order_no||'заказ')}</div>`).join('')||'<div class="mini">свободно</div>'}</div>`;}main.innerHTML=`<div class="section-title"><div><h1>Календарь</h1><p>${now.toLocaleString('ru',{month:'long',year:'numeric'})}</p></div></div><div class="calendar">${cells}</div>`;}
async function customers(){if(preview||!sb){main.innerHTML=`<div class="section-title"><div><h1>Клиенты</h1><p>История, рекомендации и бонусы</p></div></div><div class="card empty">Подключение базы активирует карточки клиентов и реферальный баланс.</div>`;return;}const {data=[]}=await sb.from('customers').select('*').order('created_at',{ascending:false}).limit(100);main.innerHTML=`<div class="section-title"><div><h1>Клиенты</h1><p>${data.length} записей</p></div></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Имя</th><th>Телефон</th><th>Реф. код</th><th>Бонус</th></tr></thead><tbody>${data.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.referral_code||'—')}</td><td>${money(x.credit_balance)}</td></tr>`).join('')}</tbody></table></div></div>`;}
function guide(){main.innerHTML=`<div class="section-title"><div><h1>Справочник</h1><p>Химия, оборудование и безопасная технология</p></div><a class="btn" target="_blank" href="../guide-app/">Открыть отдельно</a></div><div class="notice safe"><b>Правило SIR:</b> непроверенное разведение, смесь или совместимость не выдаются работнику как инструкция. При сомнении — тест или STOP.</div><iframe class="guide-frame" src="../guide-app/" title="SIR Guide"></iframe>`;}
async function finance(){const o=await getOrders(),done=o.filter(x=>x.status==='completed');const revenue=done.reduce((a,x)=>a+(+x.final_price||0),0);main.innerHTML=`<div class="section-title"><div><h1>Финансы</h1><p>Выручка, время, расходы и фактическая маржа</p></div></div><div class="grid"><div class="card metric"><span>Выполнено</span><strong>${done.length}</strong></div><div class="card metric"><span>Выручка</span><strong>${money(revenue)}</strong></div><div class="card metric"><span>Средний чек</span><strong>${money(done.length?revenue/done.length:0)}</strong></div><div class="card metric"><span>Расходы</span><strong>—</strong></div></div><div class="notice">Расходы на химию, дорогу и расходники будут учитываться по фактическим данным заказа, а не выдумываться автоматически.</div>`;}
async function team(){main.innerHTML=`<div class="section-title"><div><h1>Команда</h1><p>OWNER · ADMIN · MANAGER · WORKER</p></div></div><div class="card"><b>Раздельные аккаунты</b><p class="mini">Без общего PIN. Владелец может блокировать доступ и менять роль, но не видит пароли сотрудников.</p></div><div class="card" style="margin-top:12px"><b>Активность</b><p class="mini">Храним необходимые события безопасности и работы с заказами. Не строим скрытое наблюдение за устройством сотрудника.</p></div>`;}
async function audit(){if(preview||!sb){main.innerHTML=`<div class="section-title"><div><h1>Журнал</h1><p>Кто и что изменил</p></div></div><div class="card empty">После подключения базы здесь будут изменения статуса, цены, расписания и критических инструкций.</div>`;return;}const {data=[]}=await sb.from('audit_events').select('*').order('created_at',{ascending:false}).limit(200);main.innerHTML=`<div class="section-title"><div><h1>Журнал</h1><p>Аудит критических действий</p></div></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Время</th><th>Событие</th><th>Объект</th><th>Пользователь</th></tr></thead><tbody>${data.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('ru')}</td><td>${esc(x.action)}</td><td>${esc(x.entity_type)} ${esc(x.entity_id||'')}</td><td>${esc(x.actor_email||x.actor_id||'—')}</td></tr>`).join('')}</tbody></table></div></div>`;}
function settings(){const p=C.pricing;main.innerHTML=`<div class="section-title"><div><h1>Настройки</h1><p>Конфигурация отделена от кода и переносима</p></div></div><div class="settings-grid"><div class="card"><b>Компания</b><div class="field"><label>Телефон</label><input value="${C.phonePrimary}"></div><div class="field"><label>Радиус выезда</label><input value="${C.radiusKm} км"></div><p class="mini">После подключения базы значения будут сохраняться в app_settings и редактироваться владельцем.</p></div><div class="card"><b>Стартовые цены</b><div class="field"><label>5 мест · лёгкое</label><input type="number" value="${p.fullInterior['5'].light}"></div><div class="field"><label>5 мест · среднее</label><input type="number" value="${p.fullInterior['5'].medium}"></div><div class="field"><label>5 мест · сильное</label><input type="number" value="${p.fullInterior['5'].heavy}"></div><p class="mini">Предпросмотр не сохраняет изменения специально: бизнес-настройки нельзя оставлять только в браузере.</p></div></div>`;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
if(sb){sb.auth.getSession().then(async({data})=>{if(data.session){const {data:p}=await sb.from('profiles').select('role').eq('id',data.session.user.id).single();enter((p?.role||'worker').toUpperCase());}});}
})();
