(() => {
  const root=document.getElementById('main'),C=window.SIR_CONFIG;if(!root)return;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const lines=v=>String(v||'').split('\n').map(x=>x.trim()).filter(Boolean);
  const sb=C?.supabaseUrl&&C?.supabasePublishableKey&&window.supabase?.createClient?window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey):null;
  let rendered='';new MutationObserver(()=>queueMicrotask(enhance)).observe(root,{childList:true,subtree:true});enhance();

  async function enhance(){
    const id=root.dataset.orderId;if(!id||rendered===id||root.querySelector('#inspectionWorkspace'))return;rendered=id;
    if(root.dataset.preview==='true')return id==='demo-car'&&render(id,{preliminary_price:2400,estimated_minutes:270},[],true);
    if(!sb)return;
    const [{data:{session}},{data:order},{data:assessments=[]}]=await Promise.all([
      sb.auth.getSession(),sb.from('orders').select('id,preliminary_price,final_price,estimated_minutes').eq('id',id).single(),
      sb.from('order_assessments').select('*').eq('order_id',id).order('version',{ascending:false})]);
    if(session&&order)render(id,order,assessments,false);
  }
  function suggest(o,score,minutes,risk){const base=+o.preliminary_price||+o.final_price||0,extra=Math.max(0,minutes-(+o.estimated_minutes||0))*10,complexity=Math.max(0,score-5)*150,riskFee=risk==='high_risk'?300:0;return Math.round((base+extra+complexity+riskFee)/50)*50;}
  function render(id,order,assessments,demo){
    const latest=assessments[0],version=(latest?.version||0)+1,host=document.createElement('section');host.id='inspectionWorkspace';host.className='panel inspection-workspace';
    host.innerHTML=`<div class="panel-head"><span>Оценка и план работы</span><span class="badge">Версия ${version}</span></div>
    <div class="assessment-flow"><div class="flow-step done"><b>1. Данные клиента</b><span>Описание, фото, ориентир</span></div><div class="flow-step active"><b>2. Осмотр на месте</b><span>Фото, скрытые факторы</span></div><div class="flow-step"><b>3. Согласование</b><span>Новая цена и план</span></div></div>
    <form id="inspectionForm" class="assessment-form"><div class="notice safe"><b>Цена до осмотра: ${new Intl.NumberFormat('nb-NO').format(+order.preliminary_price||0)} NOK.</b> Расчёт ниже — рекомендация; вы подтверждаете фактическое состояние и цену.</div>
    <div class="settings-grid"><div class="field"><label>Тип оценки</label><select name="type"><option value="on_site">Осмотр на месте</option><option value="remote">По описанию и фото</option></select></div><div class="field"><label>Загрязнение, 1–10</label><input name="score" type="number" min="1" max="10" value="7" required></div><div class="field"><label>Риск</label><select name="risk"><option value="low">LOW</option><option value="caution" selected>CAUTION</option><option value="high_risk">HIGH RISK</option><option value="stop">STOP</option></select></div><div class="field"><label>Время, минут</label><input name="minutes" type="number" min="15" max="1440" step="15" value="330" required></div></div>
    <div class="field"><label>Что подтвердилось при осмотре</label><textarea name="condition" required>Сильное загрязнение сидений и ковролина, шерсть в швах и направляющих.</textarea></div>
    <div class="field"><label>Что не было видно по данным клиента</label><textarea name="hidden">Под задним сиденьем старый сладкий напиток; наполнитель влажный. На боковине водительского сиденья началось расслоение экокожи.</textarea></div>
    <div class="field"><label>Подтверждённый материал</label><input name="material" value="Ткань + экокожа" required></div>
    <div class="settings-grid"><div class="field"><label>Рекомендуемая новая цена, NOK</label><input name="price" type="number" min="0" max="100000" step="50" required></div><div class="field"><label>Причина изменения для клиента</label><textarea name="reason" required>После осмотра выявлено скрытое загрязнение под задним сиденьем и дополнительная ручная работа в швах. Объём увеличен на 1 час.</textarea></div></div>
    <h3>Обновлённый пошаговый план</h3><div class="field"><label>Порядок работ — один шаг на строку</label><textarea name="steps" rows="8">Фото всех зон и скрытого загрязнения до начала.\nСухая уборка сверху вниз; шерсть удалить до раствора.\nSpot-test ткани и экокожи.\nСиденья: секциями — контролируемое нанесение, мягкая агитация, экстракция.\nЭкокожа: минимально влажная салфетка; повреждённый участок не тереть.\nРемни: не пропитывать катушки, замки и крепления.\nКовролин и багажник после сидений; не заливать подложку.\nФинальная экстракция, вентиляция и фото результата.</textarea></div>
    <div class="field"><label>Химия и дозировка — средство / разведение / зона</label><textarea name="chemistry" rows="5">Текстильное средство из manufacturer_verified справочника — разведение строго по этикетке; наносить на рабочий участок, не заливать наполнитель.\nСовместимое средство для экокожи — минимальная концентрация по этикетке; наносить на салфетку.\nЧистая вода — контролируемая финальная экстракция; STOP при переносе красителя.</textarea></div>
    <div class="settings-grid"><div class="field"><label>Где минимум влаги</label><textarea name="moisture">Минимум влаги: экокожа, швы, ремни у катушек, разъёмы и электроника. На стабильной ткани и ковролине раствор допустим только с немедленным извлечением.</textarea></div><div class="field"><label>Повторы и сушка</label><textarea name="drying">Второй проход — после извлечения раствора и проверки влажности. Полная сушка между обычными проходами не нужна; при насыщении наполнителя остановиться и дать высохнуть.</textarea></div></div>
    <div class="field"><label>STOP — один риск на строку</label><textarea name="stops">Перенос красителя или изменение фактуры.\nУвеличение расслоения экокожи.\nПлесень, биологическое загрязнение или неизвестное вещество.\nВлага у электроники, замков ремней или разъёмов.\nПовторные проходы не улучшают результат, но повышают насыщение.</textarea></div>
    <label class="check-row"><input name="visible" type="checkbox" checked> Использовать новую цену и причину в следующем предложении клиенту</label><div class="toolbar"><button class="btn" type="button" id="recalcAssessment">Пересчитать</button><button class="btn primary" type="submit">Сохранить осмотр и новый план</button></div><div id="inspectionStatus" class="mini"></div></form>${latest?history(latest):''}`;
    root.appendChild(host);const form=host.querySelector('#inspectionForm'),recalc=()=>{const f=new FormData(form);form.elements.price.value=suggest(order,+f.get('score'),+f.get('minutes'),String(f.get('risk')));};host.querySelector('#recalcAssessment').addEventListener('click',recalc);recalc();
    form.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(form),status=host.querySelector('#inspectionStatus');if(String(f.get('risk'))==='stop'&&f.has('visible')){status.className='notice error';status.textContent='STOP: цену нельзя отправлять как готовое предложение. Сначала устраните риск или измените объём.';return;}
      const row={order_id:id,version,assessment_type:String(f.get('type')),condition_score:+f.get('score'),observed_condition:String(f.get('condition')).trim(),hidden_findings:String(f.get('hidden')).trim()||null,confirmed_material:String(f.get('material')).trim(),risk_level:String(f.get('risk')),estimated_minutes:+f.get('minutes'),proposed_price:+f.get('price'),price_change_reason:String(f.get('reason')).trim(),work_steps:lines(f.get('steps')),chemistry_plan:lines(f.get('chemistry')),moisture_plan:String(f.get('moisture')).trim(),pass_and_drying_plan:String(f.get('drying')).trim(),stop_conditions:lines(f.get('stops')),client_visible:f.has('visible')};
      if(demo){status.className='notice safe';status.textContent=`Версия ${version} сохранена в предпросмотре. Новая цена ${row.proposed_price} NOK готова к согласованию.`;host.querySelector('.badge').textContent=`Версия ${version} сохранена`;return;}
      const payload={...row};delete payload.order_id;delete payload.version;const {data,error}=await sb.rpc('save_order_assessment',{p_order:id,p_assessment:payload});if(error){status.className='notice error';status.textContent=error.message;return;}status.className='notice safe';status.textContent=`Версия ${data.version} сохранена. ${row.client_visible?'Цена готова к отправке через «Подготовить SMS клиенту».':'Цена клиента не изменена.'}`;});
  }
  function history(a){return `<details class="assessment-history"><summary>Предыдущая версия ${a.version} · ${esc(a.assessment_type==='on_site'?'осмотр':'дистанционно')}</summary><div class="kv"><span>Цена / время</span><b>${esc(a.proposed_price)} NOK · ${esc(a.estimated_minutes)} мин</b></div><div class="kv"><span>Причина</span><b>${esc(a.price_change_reason||'Без изменения')}</b></div></details>`;}
})();
