-- SIR Rens & Pleie core tables. Apply only to the dedicated SIR Supabase project.
create extension if not exists pgcrypto;

create sequence if not exists public.sir_order_no_seq start 1001;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'worker' check (role in ('owner','admin','manager','worker')),
  active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(), name text not null, phone text not null unique,
  email text, address text, referral_code text unique,
  credit_balance numeric(10,2) not null default 0 check (credit_balance>=0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_no text not null unique default ('SIR-'||to_char(current_date,'YYMM')||'-'||lpad(nextval('public.sir_order_no_seq')::text,4,'0')),
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text not null, phone text not null, address text, distance_km numeric(6,1),
  service_type text not null, vehicle_plate text, vehicle_brand text, vehicle_model text,
  vehicle_year integer, vehicle_body text, vehicle_seats integer, package_code text,
  contamination text, stains boolean not null default false, pet_hair boolean not null default false,
  odor boolean not null default false, customer_comment text,
  status text not null default 'new', risk_level text not null default 'caution',
  preliminary_price numeric(10,2), final_price numeric(10,2), estimated_minutes integer, actual_minutes integer,
  travel_fee numeric(10,2) not null default 0, chemical_cost numeric(10,2), consumables_cost numeric(10,2),
  assigned_to uuid references public.profiles(id) on delete set null, source text not null default 'website',
  referral_code_used text, internal_note text, completed_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check(status in ('new','under_review','offer_sent','awaiting_confirmation','confirmed','scheduled','in_progress','completed','customer_requested_new_time','cancelled_customer','cancelled_sir','no_show')),
  check(risk_level in ('low','caution','high_risk','stop'))
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade,
  starts_at timestamptz not null, ends_at timestamptz not null, tentative boolean not null default true,
  location_mode text not null default 'mobile', address text, buffer_minutes integer not null default 30,
  created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(),
  check(ends_at>starts_at)
);

create table if not exists public.order_events (
  id bigint generated by default as identity primary key, order_id uuid not null references public.orders(id) on delete cascade,
  event_type text not null, from_value text, to_value text, note text,
  actor_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now()
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key, actor_id uuid references public.profiles(id) on delete set null,
  actor_email text, action text not null, entity_type text not null, entity_id text,
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key, value jsonb not null, description text,
  updated_by uuid references public.profiles(id) on delete set null, updated_at timestamptz not null default now()
);

create table if not exists public.price_rules (
  id uuid primary key default gen_random_uuid(), service_code text not null, size_key text not null default 'default',
  light_price numeric(10,2), medium_price numeric(10,2), heavy_price numeric(10,2), active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb, updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(), unique(service_code,size_key)
);

create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(), referrer_customer_id uuid not null references public.customers(id) on delete cascade,
  referred_customer_id uuid references public.customers(id) on delete set null, order_id uuid references public.orders(id) on delete set null,
  referral_code text not null, referrer_credit numeric(10,2) not null default 200,
  new_customer_discount numeric(10,2) not null default 100, status text not null default 'pending',
  credited_at timestamptz, created_at timestamptz not null default now()
);

create table if not exists public.chemicals (
  id uuid primary key default gen_random_uuid(), name text not null, brand text, label_image_path text, category text,
  intended_surfaces text[] not null default '{}', prohibited_surfaces text[] not null default '{}', dilution text,
  application_method text, dwell_time text, follow_up text, warnings text, purchase_price numeric(10,2), shop_url text,
  verification_status text not null default 'unverified', source_note text, active boolean not null default true,
  updated_by uuid references public.profiles(id) on delete set null, updated_at timestamptz not null default now()
);

create table if not exists public.procedures (
  id uuid primary key default gen_random_uuid(), name text not null, surface_type text not null, contamination text,
  risk_level text not null default 'caution', steps jsonb not null default '[]'::jsonb,
  stop_conditions jsonb not null default '[]'::jsonb, verified boolean not null default false,
  version integer not null default 1, updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(), check(risk_level in ('low','caution','high_risk','stop'))
);

create table if not exists public.order_technology_cards (
  id uuid primary key default gen_random_uuid(), order_id uuid not null unique references public.orders(id) on delete cascade,
  contamination_score integer check(contamination_score between 1 and 10), material_guess text,
  material_confidence numeric(4,3) check(material_confidence between 0 and 1), risk_level text not null default 'caution',
  estimated_minutes integer, instructions jsonb not null default '[]'::jsonb, stop_conditions jsonb not null default '[]'::jsonb,
  owner_note text, reviewed_by uuid references public.profiles(id) on delete set null, reviewed_at timestamptz,
  updated_at timestamptz not null default now(), check(risk_level in ('low','caution','high_risk','stop'))
);

create index if not exists orders_status_idx on public.orders(status,created_at desc);
create index if not exists appointments_start_idx on public.appointments(starts_at);
create index if not exists audit_created_idx on public.audit_events(created_at desc);
