insert into public.chemicals(brand,name,category,intended_surfaces,prohibited_surfaces,dilution,application_method,dwell_time,follow_up,warnings,shop_url,verification_status,source_note,active,use_role,risk_level,approval_required,technology_note)
values
('Koch-Chemie','Pol Star','interior textile/leather cleaner',array['leather','alcantara','textiles','upholstery','carpet'],array[]::text[],
 '1:5–1:20 depending on soil level.',
 'Apply diluted product with spray bottle, microfibre mitt or similar. Allow to react briefly, work carefully with sponge or microfibre in the direction of the main fibres.',
 'Short reaction time; manufacturer does not specify a fixed minute value on the product page.',
 'Remove product residues and foam with a damp cloth or wet/dry vacuum. For spray-extraction/carpet machines Koch-Chemie recommends Kocentschäumer defoamer.',
 'Check colour fastness and material compatibility before use.',
 'https://bilpleiekongen.no/?s=Koch%20Chemie%20Pol%20Star&post_type=product','manufacturer_verified','https://www.koch-chemie.com/no/produkter/pol_star',true,'primary','caution',false,
 'Предпочтительный базовый очиститель SIR для совместимого текстиля/алькантары/кожи. Для потолка всё равно действует отдельная HIGH RISK процедура и минимальная влага.'),
('Koch-Chemie','Leather Star','leather care',array['smooth leather','suede','perforated leather'],array[]::text[],
 'Apply directly as supplied; no dilution step is stated in the manufacturer application instructions.',
 'First clean with a suitable cleaner such as Pol Star, wipe with a damp cloth and dry thoroughly. Shake Leather Star and apply evenly with sponge or soft microfibre.',
 'Leave to dry.',
 'Remove any excess with a soft cloth.',
 'Check compatibility as part of the SIR spot-test workflow; this is a care/protection product, not the primary dirt-removal step.',
 'https://bilpleiekongen.no/?s=Koch%20Chemie%20Leather%20Star&post_type=product','manufacturer_verified','https://www.koch-chemie.com/no/produkter/leather_star',true,'care_after_cleaning','low',false,
 'Использовать после безопасной очистки и просушки кожи, если уход входит в согласованный заказ.'),
('Koch-Chemie','Fresh Up','odour eliminator',array['textiles','upholstery','headliner','room air'],array[]::text[],
 'Sprayable ready application; manufacturer does not specify a dilution step on the product page.',
 'First remove contamination and odour sources by thorough cleaning, then spray sparingly on textiles, surfaces or rooms.',
 'No fixed dwell time specified.',
 'Allow treated material to dry and ventilate. Fresh Up is used after source cleaning, not instead of it.',
 'Protect from frost and high heat. Check suitability and compatibility before use.',
 'https://bilpleiekongen.no/?s=Koch%20Chemie%20Fresh%20Up&post_type=product','manufacturer_verified','https://www.koch-chemie.com/no/produkter/fresh_up',true,'odour_finish','caution',false,
 'Финиш после удаления источника запаха. На потолке распылять только в рамках маловлажной процедуры; не использовать как способ скрыть неочищенный источник запаха.'),
('Koch-Chemie','Glass Cleaner','glass cleaner',array['glass','mirrors','smooth surfaces'],array[]::text[],
 'Ready to use / undiluted.',
 'Spray on and wipe off.',
 'No separate dwell step specified.',
 'Wipe to a clean streak-free finish.',
 'Check suitability and compatibility before use.',
 'https://bilpleiekongen.no/produkt/koch-chemie-glass-cleaner/','manufacturer_verified','https://www.koch-chemie.com/no/produkter/glass_cleaner',true,'primary','low',false,
 'Для стекла и зеркал. Не использовать общий статус “smooth surfaces” как разрешение на неизвестный интерьерный пластик без теста.'),
('Koch-Chemie','Fleckenwasser','solvent spot remover',array['solvent-resistant textiles','glass','paint','ceramic','metal'],array['non-solvent-resistant materials'],
 'Use undiluted.',
 'Apply to the stain using a dry absorbent cloth and rub locally.',
 'No fixed dwell time specified; work locally and controlled.',
 'After local textile treatment remove residue according to the compatible textile procedure and dry the material.',
 'Check colour fastness and material compatibility before use. Organic solvent; use only on solvent-resistant substrates.',
 'https://bilpleiekongen.no/?s=Koch%20Chemie%20Fleckenwasser&post_type=product','manufacturer_verified','https://www.koch-chemie.com/de/produkte/fleckenwasser',true,'spot_only','high_risk',true,
 'Только локальная работа по пятну после теста. Не использовать как общий очиститель сиденья/дивана и не заливать материал.'),
('Koch-Chemie','Eulex','solvent residue remover',array['solvent-resistant paint','glass','ceramic','metal'],array['non-solvent-resistant materials'],
 'Use as supplied; no dilution step is specified on the product page.',
 'Use only on solvent-resistant substrates for residues such as adhesive, rubber, resin, ink, oil, grease or asphalt. SIR applies it locally after compatibility confirmation.',
 'Fast evaporating product; no fixed dwell time specified.',
 'After residue removal, inspect the substrate and perform the normal compatible finishing/cleaning step for that surface.',
 'Strong solvent-use context. Do not treat an unknown interior material as solvent-resistant without explicit compatibility confirmation.',
 'https://bilpleiekongen.no/?s=Koch%20Chemie%20Eulex&post_type=product','manufacturer_verified','https://www.koch-chemie.com/no/produkter/eulex',true,'spot_only','high_risk',true,
 'Не является универсальным средством салона. Для неизвестного пластика/текстиля автоматический выбор запрещён.')
on conflict(brand,name) do update set
 category=excluded.category,intended_surfaces=excluded.intended_surfaces,prohibited_surfaces=excluded.prohibited_surfaces,
 dilution=excluded.dilution,application_method=excluded.application_method,dwell_time=excluded.dwell_time,
 follow_up=excluded.follow_up,warnings=excluded.warnings,shop_url=excluded.shop_url,
 verification_status=excluded.verification_status,source_note=excluded.source_note,active=true,
 use_role=excluded.use_role,risk_level=excluded.risk_level,approval_required=excluded.approval_required,
 technology_note=excluded.technology_note,updated_at=now();

update public.chemicals set use_role='escalation',risk_level='caution',approval_required=false,
 technology_note='Щелочной усиленный очиститель. Для обычного текстиля SIR сначала предпочитает более щадящую подтверждённую схему. На деликатных материалах/потолке не выбирать автоматически.',updated_at=now()
where brand='Koch-Chemie' and name='Green Star';

update public.chemicals set use_role='exterior',risk_level='low',approval_required=false where name in ('NanoMagicShampoo','CARPRO ReTyre','CARPRO DarkSide');
update public.chemicals set use_role='exterior_care',risk_level='caution',approval_required=false where name='Plast Star siliconölfrei';
