insert into public.procedures(code,name,surface_type,contamination,risk_level,steps,stop_conditions,verified,version,pass_plan,drying_rule,mechanical_method,chemical_rule,source_note)
values
('textile-light','Textile — light','textile','light','low',
 '["Document existing damage and vacuum/dry-clean thoroughly before moisture.","Confirm the material and perform a spot-test for colour transfer and texture change.","Apply only the minimum amount of an approved product and follow its verified dwell instructions.","Agitate only as much as the fabric safely tolerates, then extract until as much solution as practical is removed.","Reassess before any repeat; ordinary light soil should normally end after one complete cycle."]'::jsonb,
 '["Colour transfers during test.","Texture, shade, adhesive/backing or seams change.","The filling/backing remains heavily saturated after extraction.","Unknown delicate fabric or prior chemical reaction is suspected."]'::jsonb,true,1,
 '1 complete gentle cycle. A second pass is local only after extraction and reassessment.',
 'Full drying is not required before a small local repeat on stable colourfast textile if the previous solution has been extracted well and the material is not over-wet. Final drying is required before normal use.',
 'Dry vacuum first. Use a fabric-appropriate soft/medium brush only after a spot-test; avoid excessive friction.',
 'Use only a manufacturer_verified SIR chemical explicitly suitable for the material. Start with the least aggressive effective concentration within the manufacturer range. Do not mix products unless the manufacturer explicitly permits it.',
 'SIR conservative internal procedure; product-specific dilution/dwell comes from the manufacturer_verified chemical record.'),
('textile-medium','Textile — medium','textile','medium','caution',
 '["Document damage and remove dry soil thoroughly.","Identify material and spot-test chemistry plus mechanical action.","Pretreat only soiled zones with an approved product; observe verified dwell time and do not let prohibited products dry on the surface.","Perform the main extraction cycle and remove as much solution as practical.","Inspect under good light. Repeat only remaining zones, not the entire item by default.","After the last extraction, arrange ventilation/drying and warn the customer about realistic drying time."]'::jsonb,
 '["Colour transfer, tackiness, whitening or texture change.","Foam/backing stays saturated or water migrates into seams/electronics.","Unknown stain reacts unexpectedly.","Odour worsens after wetting or biological contamination is suspected."]'::jsonb,true,1,
 'Pretreatment + 1 main extraction cycle + local repeat where the first result justifies it.',
 'For stable textile, a local repeat can follow good extraction without full drying. If the material is saturated, the stain starts wicking back, or stability is uncertain, pause and allow the zone to stabilise/partly dry before another treatment.',
 'Dry vacuum first; controlled brushing only. Increase mechanical action before increasing chemistry, but stop if fibres distort or colour moves.',
 'Only manufacturer_verified chemistry approved for the surface. Remove the previous solution before changing chemistry; never layer unknown products.',
 'SIR conservative internal procedure; product-specific dilution/dwell comes from the manufacturer_verified chemical record.'),
('textile-heavy','Textile — heavy','textile','heavy','caution',
 '["Photograph and classify stains before adding moisture.","Vacuum/dry-clean deeply and separate local stain work from the general wash.","Spot-test every stronger step before using it broadly.","Work in stages: pretreat, extract, reassess, then decide whether a second targeted stage is justified.","Remove the previous solution before changing product or strength.","Stop escalating if safe progress stalls; record the limitation instead of risking damage."]'::jsonb,
 '["Repeated passes are increasing saturation without clear improvement.","Colour/texture changes or fibres weaken.","Adhesive, backing, foam or electronics may be affected.","Biological contamination, mould, bodily fluids or unknown hazardous residue is present without a dedicated plan/PPE."]'::jsonb,true,1,
 'Multi-stage. Each stage must end with extraction and reassessment; there is no automatic fixed number of repeated full passes.',
 'Do not stack wet passes. If moisture accumulates, wicking appears, or the material is uncertain, pause for stabilisation/partial drying. Final drying is mandatory before return to use.',
 'Use the least damaging mechanical method that still works. Do not compensate for poor chemistry selection with aggressive scrubbing.',
 'Approved chemistry only; one controlled change at a time. Stronger is not automatically better. If a product change is needed, remove residues first and re-test.',
 'SIR conservative internal procedure; product-specific dilution/dwell comes from the manufacturer_verified chemical record.'),
('headliner-light','Headliner — light','headliner','light','caution',
 '["Inspect sagging, edges, previous repairs and colour stability before cleaning.","Spot-test in an inconspicuous area.","Use very low moisture and work a small section at a time.","Lift surface soil without saturating the backing/adhesive.","Reassess after the first controlled pass; do not chase a minor remaining mark with repeated wetting."]'::jsonb,
 '["Any sagging, softening, bubbling or edge lift.","Colour transfer or visible shade change.","Unknown adhesive condition or prior headliner repair."]'::jsonb,true,1,
 'Normally 1 controlled low-moisture pass. Any repeat is small and local.',
 'A local repeat should wait until the treated zone is stable and no softening/sagging is developing. When adhesive condition is uncertain, allow partial drying before deciding on another step.',
 'Soft microfibre/soft brush only as the material tolerates. No aggressive scrubbing and no flood extraction.',
 'Use only a manufacturer_verified product suitable for the headliner/textile and in the minimum practical amount. Never saturate the backing.',
 'SIR high-caution headliner procedure. Adhesive condition cannot be confirmed from a photo alone.'),
('headliner-medium','Headliner — medium','headliner','medium','high_risk',
 '["Photograph and inspect the entire headliner, especially edges and existing sagging.","Spot-test chemistry and very gentle mechanical action.","Work in small zones with controlled low moisture.","Complete one zone, remove residues/moisture and inspect stability before moving on.","A second local treatment is permitted only when the first zone remains stable and the expected benefit outweighs the adhesive risk."]'::jsonb,
 '["Sagging, adhesive softening, bubbling or seam/edge movement.","Colour transfer or nap/texture damage.","Need for repeated wetting to obtain cosmetic perfection."]'::jsonb,true,1,
 '1 controlled pass by small zones; second pass only on selected spots after stability check.',
 'Do not immediately re-wet a questionable area. Let it stabilise/partly dry before deciding. Full drying is required before judging final adhesive stability.',
 'Very gentle local agitation only. Avoid extractor flooding and hard brushes.',
 'Use the minimum amount of a manufacturer_verified compatible product. Do not switch to stronger chemistry simply because a stain remains.',
 'SIR high-caution headliner procedure. Adhesive condition cannot be confirmed from a photo alone.'),
('headliner-heavy','Headliner — heavy','headliner','heavy','high_risk',
 '["Do not promise full stain removal before physical inspection.","Inspect adhesive integrity, sagging and previous repairs; photograph findings.","Spot-test the least invasive method.","Treat only sections that can be cleaned without saturating the backing.","If meaningful cleaning requires repeated wetting, stop and consult OWNER before proceeding."]'::jsonb,
 '["Existing or developing sagging.","Adhesive/backing softens.","Heavy nicotine/unknown residues require chemistry outside the verified procedure.","Customer expectation would require unsafe repeated saturation."]'::jsonb,true,1,
 'No automatic multi-pass plan. One cautious test zone determines whether further cleaning is safe; OWNER review for escalation.',
 'Allow test zones to stabilise/dry before escalation. Do not perform back-to-back wet passes on a high-risk headliner.',
 'Minimum mechanical action. No aggressive brush and no flood extraction.',
 'Only verified compatible chemistry at controlled moisture. If safe chemistry does not achieve an acceptable result, document the limitation rather than escalate blindly.',
 'SIR high-risk headliner procedure. Adhesive condition cannot be confirmed from a photo alone.'),
('mattress-light','Mattress — light','mattress','light','low',
 '["Vacuum both accessible surfaces and seams thoroughly.","Identify cover material and spot-test.","Use a controlled textile-cleaning cycle without soaking the inner core.","Extract thoroughly and arrange strong ventilation."]'::jsonb,
 '["Colour transfer or fabric distortion.","Core becomes heavily saturated.","Mould, bodily fluids or biological contamination requires a separate risk plan."]'::jsonb,true,1,
 '1 controlled cycle; local repeat only if the cover remains stable and not saturated.',
 'Full drying before sleeping/use is mandatory. Do not return a damp mattress for immediate use.',
 'Vacuum first; soft fabric-safe agitation only.',
 'Manufacturer_verified textile chemistry compatible with the cover. Do not soak the core and do not mask odour with fragrance.',
 'SIR conservative mattress procedure.'),
('mattress-medium','Mattress — medium','mattress','medium','caution',
 '["Vacuum seams and surface deeply before moisture.","Classify stains and spot-test.","Pretreat only affected areas, then perform controlled extraction.","Reassess after extraction and repeat remaining local areas only.","Ventilate until fully dry before use."]'::jsonb,
 '["Moisture is reaching deep into the core faster than it can be extracted.","Biological contamination is suspected.","Colour/texture changes."]'::jsonb,true,1,
 'Pretreatment + 1 main controlled cycle + local repeat as required.',
 'A local repeat may follow good extraction on a stable cover, but the mattress must be fully dry before return to use. If core saturation is suspected, pause and dry before continuing.',
 'Gentle textile-safe agitation only; protect seams and quilting.',
 'Use only manufacturer_verified chemistry compatible with the cover; remove residues thoroughly and avoid stacking products.',
 'SIR conservative mattress procedure.'),
('mattress-heavy','Mattress — heavy','mattress','heavy','high_risk',
 '["Photograph and classify stains before wetting.","Assess whether the contamination is appropriate for normal cleaning or requires refusal/special handling.","Work locally and in stages to avoid saturating the core.","Extract after every stage and reassess.","Stop if safe drying cannot be assured."]'::jsonb,
 '["Mould or significant biological contamination without dedicated protocol/PPE.","Deep core saturation.","Persistent odour source cannot be safely removed.","Material changes during testing."]'::jsonb,true,1,
 'Staged local treatment only; no repeated full saturation cycles.',
 'Dry/stabilise whenever moisture begins accumulating in the core. Full drying before use is mandatory and may require extended ventilation.',
 'Controlled soft agitation; do not damage quilting or force liquid into seams.',
 'Verified chemistry only. Do not increase chemical strength or combine products without a documented compatible method.',
 'SIR high-caution mattress procedure.'),
('plastic-light','Interior plastic — light','interior_plastic','light','low',
 '["Identify sensitive coatings, screens, piano-black trim and printed symbols.","Apply product to the cloth/brush rather than flooding switches or seams.","Wipe a small test area, then clean evenly and remove residue."]'::jsonb,
 '["Whitening, tackiness, gloss/colour change or symbol damage.","Liquid enters switches/electronics."]'::jsonb,true,1,
 '1 controlled wipe/cleaning cycle; repeat only a local dirty area after reassessment.',
 'No drying interval is normally required for a second light wipe once residue is removed, but the surface should not remain wet around electronics or seams.',
 'Microfibre and soft detailing brush; minimal pressure on coated/printed surfaces.',
 'Only manufacturer_verified interior-safe chemistry. Never use exterior dressings or strong alkaline cleaner on an unknown interior surface without compatibility confirmation.',
 'SIR conservative interior-surface procedure.'),
('plastic-medium','Interior plastic — medium','interior_plastic','medium','caution',
 '["Inspect coatings and existing whitening/scratches before cleaning.","Spot-test a hidden area.","Use controlled chemistry on microfibre/brush, not direct flooding.","Agitate textured areas gently, wipe residue, inspect colour/gloss, then repeat locally if required."]'::jsonb,
 '["Whitening, tackiness, colour/gloss shift or coating lift.","Previous chemical damage becomes more visible.","Electronics cannot be protected from liquid."]'::jsonb,true,1,
 '1 main controlled cycle + local repeat on textured/dirty areas.',
 'A local second wipe may be immediate after the first residue is removed and the surface is stable. Stop instead of repeating if whitening/tackiness appears.',
 'Microfibre/soft brush. Increase contact time only within product instructions; do not compensate with hard scrubbing.',
 'Verified product explicitly suitable for interior plastics/coatings. Avoid unverified strong alkali on sensitive trim.',
 'SIR conservative interior-surface procedure.'),
('plastic-heavy','Interior plastic — heavy','interior_plastic','heavy','caution',
 '["Separate actual soil from existing chemical damage before starting.","Spot-test every stronger step.","Clean in stages with controlled product amount and complete residue removal between stages.","If staining/whitening is permanent coating damage, stop cleaning escalation and document it."]'::jsonb,
 '["Whitening/tackiness worsens.","Coating or printed symbols lift.","A stronger chemical would be needed without verified compatibility."]'::jsonb,true,1,
 'Staged local cleaning; no fixed automatic number of repeats.',
 'Remove residue and let the surface stabilise before stronger escalation. Existing chemical damage must not be treated as removable dirt.',
 'Soft brush/microfibre only; protect electronics and delicate coatings.',
 'Use verified interior-safe chemistry only. If safe product cannot remove the mark, treat it as possible damage and STOP rather than escalating.',
 'SIR conservative interior-surface procedure.'),
('leather-light','Leather / coated leather — light','leather','light','caution',
 '["Determine whether the surface is coated leather, synthetic leather or damaged/unfinished leather.","Spot-test cleaner and colour stability.","Work a small area with dedicated leather-safe product and soft brush/cloth.","Remove residue and allow the surface to dry before optional approved protection/care."]'::jsonb,
 '["Colour transfers.","Finish becomes sticky, dull, patchy or lifts.","Cracks/abrasions expose unstable colour layer."]'::jsonb,true,1,
 '1 gentle cleaning cycle; local repeat only after checking the finish.',
 'Let the cleaned area dry/stabilise before applying any care/protection product. Re-cleaning should not keep the finish continuously wet.',
 'Soft leather brush/microfibre; low pressure.',
 'Dedicated manufacturer_verified leather-safe chemistry only. Do not use textile extraction chemistry as a substitute.',
 'SIR conservative leather procedure.'),
('leather-medium','Leather / coated leather — medium','leather','medium','caution',
 '["Inspect finish wear, cracks, dye transfer and previous dressings.","Spot-test dedicated cleaner.","Clean in small sections, remove residue immediately and inspect the finish.","Repeat locally only if the finish remains stable.","Apply care/protection only if compatible and part of the agreed procedure."]'::jsonb,
 '["Colour/finish transfers.","Surface becomes sticky, patchy or excessively matte/glossy.","Cleaning reveals unstable damaged coating."]'::jsonb,true,1,
 '1 main small-section cycle + local repeat where finish remains stable.',
 'Remove residue between passes and let questionable areas stabilise before repeating. Dry before protection/care.',
 'Soft leather brush/microfibre; no abrasive pad or extractor saturation.',
 'Dedicated verified leather-safe product only; do not escalate to alkaline textile cleaner.',
 'SIR conservative leather procedure.'),
('leather-heavy','Leather / coated leather — heavy','leather','heavy','high_risk',
 '["Photograph wear/damage and distinguish dirt from failed coating/dye.","Test the mildest dedicated leather-safe method first.","Work section by section and stop escalation when the finish becomes unstable.","Explain permanent coating damage rather than attempting to scrub it away."]'::jsonb,
 '["Dye/finish transfers or coating lifts.","Cracks or abrasions worsen.","Required chemistry is outside verified leather-safe products."]'::jsonb,true,1,
 'No automatic aggressive multi-pass plan. Repeat only while the coating is demonstrably stable.',
 'Let suspect areas dry/stabilise before deciding on another pass. Do not keep damaged coating wet.',
 'Very soft brush/microfibre only; no abrasive escalation.',
 'Dedicated verified leather chemistry only. If safe cleaning reaches its limit, stop and document permanent damage.',
 'SIR high-caution leather procedure.')
on conflict(code) do update set
 name=excluded.name,surface_type=excluded.surface_type,contamination=excluded.contamination,risk_level=excluded.risk_level,
 steps=excluded.steps,stop_conditions=excluded.stop_conditions,verified=excluded.verified,pass_plan=excluded.pass_plan,
 drying_rule=excluded.drying_rule,mechanical_method=excluded.mechanical_method,chemical_rule=excluded.chemical_rule,
 source_note=excluded.source_note,updated_at=now();
